import os from "node:os";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { head, put } from "@vercel/blob";
import { ulid } from "ulid";

import type { FetchBundleResult, StoreBundleResult } from "./types.ts";

// ULIDs generated by `ulid()` are canonical, uppercase, 26-character values.
// The first character is limited to 0-7 because the timestamp occupies 48 bits.
const BUNDLE_ID_PATTERN = /^[0-7][0-9A-HJKMNP-TV-Z]{25}$/;

export function isValidBundleId(id: string): boolean {
  return BUNDLE_ID_PATTERN.test(id);
}

function assertValidBundleId(id: string): void {
  if (!isValidBundleId(id)) {
    throw new Error("Invalid bundle ID");
  }
}

function resolveLocalBlobDir(): string | null {
  const explicitDir = String(process.env.LOCAL_BLOB_DIR ?? "").trim();
  if (explicitDir) {
    return explicitDir;
  }

  if (String(process.env.BLOB_READ_WRITE_TOKEN ?? "").trim()) {
    return null;
  }

  const isDevLike =
    String(process.env.OPENRIND_DESKTOP_DEV_MODE ?? "") === "1" ||
    String(process.env.NODE_ENV ?? "").trim() !== "production";

  if (!isDevLike) {
    return null;
  }

  return path.join(os.tmpdir(), "openrind-desktop-share-blobs");
}

function resolveBundlePathname(id: string): string {
  assertValidBundleId(id);
  return `bundles/${id}.json`;
}

function resolveLocalBundlePath(localBlobDir: string, id: string): string {
  const storageRoot = path.resolve(localBlobDir);
  const targetPath = path.resolve(storageRoot, resolveBundlePathname(id));
  const relativePath = path.relative(storageRoot, targetPath);

  if (
    !relativePath ||
    path.isAbsolute(relativePath) ||
    relativePath === ".." ||
    relativePath.startsWith(`..${path.sep}`)
  ) {
    throw new Error("Bundle path escapes local blob storage");
  }

  return targetPath;
}

async function storeBundleJsonLocally(rawJson: string): Promise<StoreBundleResult> {
  const id = ulid();
  const pathname = resolveBundlePathname(id);
  const localBlobDir = resolveLocalBlobDir();

  if (!localBlobDir) {
    throw new Error("Local blob storage is not configured");
  }

  const targetPath = resolveLocalBundlePath(localBlobDir, id);
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, Buffer.from(String(rawJson), "utf8"));

  return { id, pathname };
}

async function fetchBundleJsonLocally(id: string): Promise<FetchBundleResult> {
  const pathname = resolveBundlePathname(id);
  const localBlobDir = resolveLocalBlobDir();

  if (!localBlobDir) {
    throw new Error("Local blob storage is not configured");
  }

  const targetPath = resolveLocalBundlePath(localBlobDir, id);
  const rawBuffer = await readFile(targetPath);
  return {
    blob: {
      url: `file://${targetPath}`,
      contentType: "application/json",
    },
    rawBuffer,
    rawJson: rawBuffer.toString("utf8"),
  };
}

export async function storeBundleJson(rawJson: string): Promise<StoreBundleResult> {
  if (resolveLocalBlobDir()) {
    return storeBundleJsonLocally(rawJson);
  }

  const id = ulid();
  const pathname = resolveBundlePathname(id);
  const buffer = Buffer.from(String(rawJson), "utf8");

  await put(pathname, buffer, {
    access: "public",
    contentType: "application/json",
    addRandomSuffix: false,
  });

  return { id, pathname };
}

export async function fetchBundleJsonById(id: string): Promise<FetchBundleResult> {
  if (resolveLocalBlobDir()) {
    return fetchBundleJsonLocally(id);
  }

  const pathname = resolveBundlePathname(id);
  const blob = await head(pathname);
  const response = await fetch(blob.url, { method: "GET" });

  if (!response.ok) {
    throw new Error("Upstream blob fetch failed");
  }

  const rawBuffer = Buffer.from(await response.arrayBuffer());
  return {
    blob,
    rawBuffer,
    rawJson: rawBuffer.toString("utf8"),
  };
}
