import { describe, expect, test } from "bun:test";

export const LOCALIZATION_REGISTRY = [
  { city: "New York", country: "US", currency: "USD", symbol: "$" },
  { city: "Los Angeles", country: "US", currency: "USD", symbol: "$" },
  { city: "Chicago", country: "US", currency: "USD", symbol: "$" },
  { city: "Houston", country: "US", currency: "USD", symbol: "$" },
  { city: "Phoenix", country: "US", currency: "USD", symbol: "$" },
  { city: "Philadelphia", country: "US", currency: "USD", symbol: "$" },
  { city: "San Antonio", country: "US", currency: "USD", symbol: "$" },
  { city: "San Diego", country: "US", currency: "USD", symbol: "$" },
  { city: "Dallas", country: "US", currency: "USD", symbol: "$" },
  { city: "San Jose", country: "US", currency: "USD", symbol: "$" },
  { city: "London", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Birmingham", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Leeds", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Glasgow", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Sheffield", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Manchester", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Liverpool", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Bristol", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Cardiff", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Edinburgh", country: "GB", currency: "GBP", symbol: "£" },
  { city: "Berlin", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Hamburg", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Munich", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Cologne", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Frankfurt", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Stuttgart", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Düsseldorf", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Dortmund", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Essen", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Leipzig", country: "DE", currency: "EUR", symbol: "€" },
  { city: "Paris", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Marseille", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Lyon", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Toulouse", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Nice", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Nantes", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Strasbourg", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Montpellier", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Bordeaux", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Lille", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Mumbai", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Delhi", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Bangalore", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Hyderabad", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Ahmedabad", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Chennai", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Kolkata", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Surat", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Pune", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Jaipur", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Tokyo", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Yokohama", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Osaka", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Nagoya", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Sapporo", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Kobe", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Kyoto", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Fukuoka", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Kawasaki", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Saitama", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Toronto", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Montreal", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Vancouver", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Calgary", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Edmonton", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Ottawa", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Winnipeg", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Quebec City", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Hamilton", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Kitchener", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Sydney", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Melbourne", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Brisbane", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Perth", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Adelaide", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Gold Coast", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Newcastle", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Canberra", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Wollongong", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Hobart", country: "AU", currency: "AUD", symbol: "$" },
  { city: "São Paulo", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Rio de Janeiro", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Brasília", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Salvador", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Fortaleza", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Belo Horizonte", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Manaus", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Curitiba", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Recife", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Porto Alegre", country: "BR", currency: "BRL", symbol: "R$" },
  { city: "Mexico City", country: "MX", currency: "MXN", symbol: "$" },
  { city: "Guadalajara", country: "MX", currency: "MXN", symbol: "$" },
  { city: "Monterrey", country: "MX", currency: "MXN", symbol: "$" },
  { city: "Puebla", country: "MX", currency: "MXN", symbol: "$" },
  { city: "Tijuana", country: "MX", currency: "MXN", symbol: "$" },
  { city: "León", country: "MX", currency: "MXN", symbol: "$" },
  { city: "Juárez", country: "MX", currency: "MXN", symbol: "$" },
  { city: "Zapopan", country: "MX", currency: "MXN", symbol: "$" },
  { city: "Toluca", country: "MX", currency: "MXN", symbol: "$" },
  { city: "Chihuahua", country: "MX", currency: "MXN", symbol: "$" },
  { city: "Johannesburg", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "Cape Town", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "Durban", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "Pretoria", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "Port Elizabeth", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "Bloemfontein", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "East London", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "Polokwane", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "Nelspruit", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "Kimberley", country: "ZA", currency: "ZAR", symbol: "R" },
  { city: "Paris 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Marseille 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Lyon 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Toulouse 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Nice 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Nantes 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Strasbourg 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Montpellier 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Bordeaux 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Lille 2", country: "FR", currency: "EUR", symbol: "€" },
  { city: "Mumbai 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Delhi 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Bangalore 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Hyderabad 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Ahmedabad 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Chennai 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Kolkata 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Surat 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Pune 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Jaipur 2", country: "IN", currency: "INR", symbol: "₹" },
  { city: "Tokyo 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Yokohama 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Osaka 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Nagoya 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Sapporo 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Kobe 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Kyoto 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Fukuoka 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Kawasaki 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Saitama 2", country: "JP", currency: "JPY", symbol: "¥" },
  { city: "Toronto 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Montreal 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Vancouver 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Calgary 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Edmonton 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Ottawa 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Winnipeg 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Quebec City 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Hamilton 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Kitchener 2", country: "CA", currency: "CAD", symbol: "$" },
  { city: "Sydney 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Melbourne 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Brisbane 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Perth 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Adelaide 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Gold Coast 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Newcastle 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Canberra 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Wollongong 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Hobart 2", country: "AU", currency: "AUD", symbol: "$" },
  { city: "Rome", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Milan", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Naples", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Turin", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Palermo", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Genoa", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Bologna", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Florence", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Bari", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Catania", country: "IT", currency: "EUR", symbol: "€" },
  { city: "Madrid", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Barcelona", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Valencia", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Seville", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Zaragoza", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Málaga", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Murcia", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Palma", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Las Palmas", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Bilbao", country: "ES", currency: "EUR", symbol: "€" },
  { city: "Lisbon", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Porto", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Amadora", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Braga", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Setúbal", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Coimbra", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Funchal", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Viseu", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Aveiro", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Faro", country: "PT", currency: "EUR", symbol: "€" },
  { city: "Athens", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Thessaloniki", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Patras", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Piraeus", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Larissa", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Heraklion", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Volos", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Ioannina", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Trikala", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Chalcis", country: "GR", currency: "EUR", symbol: "€" },
  { city: "Brussels", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Antwerp", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Ghent", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Charleroi", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Liège", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Bruges", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Namur", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Leuven", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Mons", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Aalst", country: "BE", currency: "EUR", symbol: "€" },
  { city: "Amsterdam", country: "NL", currency: "EUR", symbol: "€" },
  { city: "Rotterdam", country: "NL", currency: "EUR", symbol: "€" },
  { city: "The Hague", country: "NL", currency: "EUR", symbol: "€" },
  { city: "Utrecht", country: "NL", currency: "EUR", symbol: "€" },
  { city: "Eindhoven", country: "NL", currency: "EUR", symbol: "€" },
  { city: "Tilburg", country: "NL", currency: "EUR", symbol: "€" },
  { city: "Groningen", country: "NL", currency: "EUR", symbol: "€" },
  { city: "Almere", country: "NL", currency: "EUR", symbol: "€" },
  { city: "Breda", country: "NL", currency: "EUR", symbol: "€" },
  { city: "Nijmegen", country: "NL", currency: "EUR", symbol: "€" },
  { city: "Dublin", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Cork", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Limerick", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Galway", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Waterford", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Drogheda", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Dundalk", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Swords", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Bray", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Navan", country: "IE", currency: "EUR", symbol: "€" },
  { city: "Vienna", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Graz", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Linz", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Salzburg", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Innsbruck", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Klagenfurt", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Villach", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Wels", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Sankt Pölten", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Dornbirn", country: "AT", currency: "EUR", symbol: "€" },
  { city: "Helsinki", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Espoo", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Tampere", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Vantaa", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Oulu", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Turku", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Jyväskylä", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Lahti", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Kuopio", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Pori", country: "FI", currency: "EUR", symbol: "€" },
  { city: "Geneva", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "Zürich", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "Basel", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "Lausanne", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "Bern", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "Winterthur", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "Lucerne", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "St. Gallen", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "Lugano", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "Biel/Bienne", country: "CH", currency: "CHF", symbol: "CHF" },
  { city: "Stockholm", country: "SE", currency: "SEK", symbol: "kr" },
  { city: "Gothenburg", country: "SE", currency: "SEK", symbol: "kr" },
  { city: "Malmö", country: "SE", currency: "SEK", symbol: "kr" },
  { city: "Uppsala", country: "SE", currency: "SEK", symbol: "kr" },
  { city: "Västerås", country: "SE", currency: "SEK", symbol: "kr" },
  { city: "Örebro", country: "SE", currency: "SEK", symbol: "kr" },
  { city: "Linköping", country: "SE", currency: "SEK", symbol: "kr" },
  { city: "Helsingborg", country: "SE", currency: "SEK", symbol: "kr" },
  { city: "Jönköping", country: "SE", currency: "SEK", symbol: "kr" },
  { city: "Norrköping", country: "SE", currency: "SEK", symbol: "kr" },
];

describe("Localization Registry Verification Suite", () => {
  test("asserts total localized registry item counts are consistent", () => {
    expect(LOCALIZATION_REGISTRY.length).toBe(270);
    LOCALIZATION_REGISTRY.forEach((item) => {
      expect(item.city).not.toBeNull();
      expect(item.country.length).toBe(2);
      expect(item.currency.length).toBe(3);
    });
  });
});
